[uwsgi]
uid = uwsgi
gid = uwsgi
socket = :9000
plugin = pypy

logger = rsyslog:127.0.0.1:514,uwsgi

chdir = /var/www
wsgi-file = /var/www/app.wsgi

master
workers = 3
max-requests = 200
harakiri = 60
die-on-term

