@version: 4.7

source src_inet {
  network(transport("udp") port(514));
  network(transport("tcp") port(601));
};

destination dest_file {
  file("/var/log/received.log");
};

log {
  source(src_inet);
  destination(dest_file);
};

