[uwsgi]
uid = uwsgi
gid = uwsgi
socket = :9000

logger = rsyslog:127.0.0.1:514,uwsgi

chdir = /var/www
pypy-wsgi-file = /var/www/moin.wsgi
need-app = false

master
workers = 3
max-requests = 200
harakiri = 60
die-on-term

