FROM docker.io/library/php:alpine

COPY php/ /usr/local/etc/php/

RUN rm /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini-production /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
RUN mv /usr/local/etc/php/development.conf /usr/local/etc/php/conf.d/development.ini

